"""initial_schema

Revision ID: 6848f63549eb
Revises: 
Create Date: 2026-06-19 21:22:09.729195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6848f63549eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('fullName', sa.String(length=191), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('phone', sa.String(length=191), nullable=False),
    sa.Column('password', sa.String(length=191), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('viator_alerts',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('viator_reference', sa.String(length=191), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('pickup_date_label', sa.String(length=200), nullable=False),
    sa.Column('received_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('booking_uuid', sa.String(length=191), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dismissed_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viator_reference')
    )
    op.create_index('viator_alerts_dismissed_at_received_at_idx', 'viator_alerts', ['dismissed_at', 'received_at'], unique=False)
    op.create_table('Driver',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=True),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('phone', sa.String(length=191), nullable=False),
    sa.Column('password', sa.String(length=191), nullable=False),
    sa.Column('photoUrl', sa.String(length=191), nullable=True),
    sa.Column('ratingAverage', sa.Float(), nullable=True),
    sa.Column('ratingCount', sa.Integer(), nullable=False),
    sa.Column('isAvailable', sa.Boolean(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('Booking',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('uuid', sa.String(length=191), nullable=False),
    sa.Column('booking_reference', sa.String(length=191), nullable=False),
    sa.Column('userId', sa.String(length=191), nullable=False),
    sa.Column('driverId', sa.String(length=191), nullable=True),
    sa.Column('customer_name', sa.String(length=191), nullable=True),
    sa.Column('customer_email', sa.String(length=191), nullable=True),
    sa.Column('customer_phone', sa.String(length=191), nullable=True),
    sa.Column('flight_number', sa.String(length=191), nullable=True),
    sa.Column('return_time', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('pickupLocation', sa.JSON(), nullable=False),
    sa.Column('dropoffLocation', sa.JSON(), nullable=False),
    sa.Column('scheduledTime', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=191), nullable=False),
    sa.Column('luggageCount', sa.Integer(), nullable=False),
    sa.Column('passengerCount', sa.Integer(), nullable=False),
    sa.Column('infantCarrierCount', sa.Integer(), nullable=False),
    sa.Column('childSeatCount', sa.Integer(), nullable=False),
    sa.Column('boosterCount', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=191), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('completed_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.ForeignKeyConstraint(['driverId'], ['Driver.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('Car',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('driverId', sa.String(length=191), nullable=False),
    sa.Column('carName', sa.String(length=191), nullable=False),
    sa.Column('carNumber', sa.String(length=191), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driverId'], ['Driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carNumber'),
    sa.UniqueConstraint('driverId')
    )
    op.create_table('driver_invoices',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('driver_id', sa.String(length=191), nullable=False),
    sa.Column('full_name', sa.String(length=191), nullable=False),
    sa.Column('phone_number', sa.String(length=191), nullable=False),
    sa.Column('booking_reference', sa.String(length=191), nullable=False),
    sa.Column('pickup_date', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('pickup_kind', sa.Enum('LOCATION', 'AIRPORT', name='invoiceaddresskind'), nullable=False),
    sa.Column('pickup_address', sa.String(length=191), nullable=True),
    sa.Column('pickup_airline', sa.String(length=191), nullable=True),
    sa.Column('pickup_flight_no', sa.String(length=191), nullable=True),
    sa.Column('dropoff_kind', sa.Enum('LOCATION', 'AIRPORT', name='invoiceaddresskind'), nullable=False),
    sa.Column('dropoff_address', sa.String(length=191), nullable=True),
    sa.Column('dropoff_airline', sa.String(length=191), nullable=True),
    sa.Column('dropoff_flight_no', sa.String(length=191), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_booking_uuid', sa.String(length=191), nullable=True),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('child_seats_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['Driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_verification_codes',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('driver_id', sa.String(length=191), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['Driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('driver_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_verification_codes')
    op.drop_table('driver_invoices')
    op.drop_table('Car')
    op.drop_table('Booking')
    op.drop_table('Driver')
    op.drop_index('viator_alerts_dismissed_at_received_at_idx', table_name='viator_alerts')
    op.drop_table('viator_alerts')
    op.drop_table('User')
    # ### end Alembic commands ###
